// <auto-generated />
namespace JodyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class next01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(next01));
        
        string IMigrationMetadata.Id
        {
            get { return "201805072010495_next01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
